<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyH1Kxv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyH1Kxv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyH1Kxv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyH1Kxv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyH1Kxv\App_KernelDevDebugContainer([
    'container.build_hash' => 'XyH1Kxv',
    'container.build_id' => 'ebe1fc0f',
    'container.build_time' => 1692443256,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyH1Kxv');
